# Generated by Django 3.1.3 on 2020-11-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('created_info', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update_info', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
    ]
