# Generated by Django 3.1.3 on 2020-11-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201113_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='picture',
        ),
    ]
